helix:
  client_id: SHAKEN_TWITCH_CLIENT_ID
  client_secret: SHAKEN_TWITCH_CLIENT_SECRET

spotify:
  client_id: SHAKEN_SPOTIFY_CLIENT_ID
  client_secret: SHAKEN_SPOTIFY_CLIENT_SECRET

github:
  oauth_token: SHAKEN_GITHUB_OAUTH_TOKEN
